// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // During next build, DATABASE_URL may not be set.
    // Provide a dummy URL so PrismaClient can be instantiated for type checking.
    // Actual DB connections only happen at runtime.
    url: process.env["DATABASE_URL"] || "postgresql://build:build@localhost:5432/build",
  },
});
