#!/usr/bin/env bash
set -e

# BoringBlog — Local Development Setup Script
# Generates .env with secure random values and sensible defaults.

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "⚠️  $ENV_FILE already exists. Remove it first if you want to regenerate."
  exit 1
fi

# Generate a random session secret
SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null \
  || openssl rand -base64 32 \
  || echo "please-change-me-to-a-random-32-char-string")

cat > "$ENV_FILE" << EOF
# ─── Generated by scripts/setup.sh ───────────────────────────────

# 数据库 / Database (matches docker-compose.yml defaults)
DATABASE_URL="postgresql://boringblog:boringblog@localhost:5432/boringblog"

# 会话加密 / Session encryption
SESSION_SECRET="${SESSION_SECRET}"

# 邮件服务 / Email (Azure Communication Services)
# Leave as-is for local dev — email sending will be skipped gracefully.
ACS_CONNECTION_STRING=""
ACS_SENDER_ADDRESS=""

# Azure Blob Storage
# Leave empty for local dev — images save to public/uploads/ as fallback.
AZURE_STORAGE_ACCOUNT_NAME=""
AZURE_STORAGE_ACCOUNT_KEY=""
AZURE_STORAGE_CONTAINER_NAME="images"

# 网站域名 / Site URL
NEXT_PUBLIC_SITE_URL="http://localhost:3000"

# 种子用户 / Seed users (used by: npx prisma db seed)
SEED_ADMIN_EMAIL="admin@example.com"
SEED_ADMIN_PASSWORD="admin123"
SEED_ADMIN_NAME="管理员"
SEED_AUTHOR_EMAIL="author@example.com"
SEED_AUTHOR_PASSWORD="author123"
SEED_AUTHOR_NAME="作者"
EOF

echo "✅ Created $ENV_FILE with:"
echo "   - Random SESSION_SECRET"
echo "   - Local PostgreSQL defaults (matching docker-compose.yml)"
echo "   - Empty ACS/Storage (email + blob upload disabled — fine for local dev)"
echo "   - Default seed users: admin@example.com / admin123, author@example.com / author123"
echo ""
echo "Next steps:"
echo "  docker compose up -d        # Start PostgreSQL"
echo "  npm install                  # Install dependencies"
echo "  npx prisma generate          # Generate Prisma client"
echo "  npx prisma migrate dev       # Run migrations"
echo "  npx prisma db seed           # Seed users"
echo "  npm run dev                  # Start dev server"
